### ISSUE TITLE
Sanitize path

### ISSUE THREAD

**Issue by davidtavarez** [Kyonru/Assets-Renamer#6]
The script should verify and sanitize the destination path properly.

**Comment by hectoraristy** [comment]
I think we can validate this by looking if the last character of the path does has a '/'. What do you think @davidtavarez @Kyonru ?

**Comment by davidtavarez** [comment]
We could add `os.path.abspath(args.path + '/' + directory)` here https://github.com/Kyonru/Assets-Renamer/blob/d58cf6b50376b09de3f2a8b57ad18a8d084324ac/RenamerMaterialDesign.py#L59

**Comment by davidtavarez** [comment]
@Kyonru I can do it.

**Comment by davidtavarez** [comment]
PR placed https://github.com/Kyonru/Assets-Renamer/pull/14
