### ISSUE TITLE
Move file to a folder

### ISSUE THREAD

**Issue by Kyonru** [Kyonru/Assets-Renamer#8]
As an user I need to move the files to my project.
The script needs the possibility of having getting a path where the files are going to be moved.

**Comment by hectoraristy** [comment]
I created a PR #13 for this issue. Let me know if you see something wrong in the code. I tested with and without destination param

**Comment by Kyonru** [comment]
I´ll be updating the readme, nice job!

**Comment by davidtavarez** [comment]
Nice!
